baseURL: http://example.org/                  # Hosting location.
languageCode: en-us                           # Locale
title: Acme Corporation                       # Name of the website
publishDir: docs                              # Output folder
theme: github.com/hugoinaction/Eclectic       # Name of the theme
enableEmoji: true                             # Enable Emojis
