baseURL: https://example.org                  # Hosting location
languageCode: en-us                           # Locale
title: Acme Corporation                       # Name of the website
publishDir: docs                              # Output folder
theme: github.com/hugoinaction/Eclectic       # Name of the theme
enableEmoji: true                             # Enable Emojis
pygmentsCodefences: true                      # Enable Code fences
pygmentsUseClasses: false                     # Use CSS instead of inline styling
pygmentsStyle: monokai                        # Inline style to use
pygmentsCodefencesGuessSyntax: true           # Guess language if not provided
pygmentsUseClassic: false                     # Use pygments instead of chroma
pygmentsOptions: "linenos=true"               # Parameters to pass to pygments
