main:                                       #    - Name of the menu
  - identifier: home                        #       - Identifier
    name: Home                              #       - Display name (theme specific key)
    url: /                                  #       - Target URL
    weight: 1                               #       - Sorting order
  - identifier: about
    name: About
    url: /about
    weight: 2
  - identifier: contact
    name: Contact
    url: /contact
    weight: 3
