baseURL = "http://example.org/"                       # URL of the website
languageCode = "en-us"                                # Locale
title = "Acme Corporation"                            # Name of the website
theme = "github.com/hugoinaction/Eclectic"            # Name of the theme

[author]                                              # Information about the website author
facebook = "https://facebook.com/example"
twitter = "https://twitter.com/example"
email = "contact@example.org"
name = "Acme Corporation"
location = "New York"
phone = "(999) 999-9999"
hours = "**Mon-Fri:** 9:00AM - 6:00PM, ET"

[menu]                                                # Menu placement

  [[menu.main]]                                       #    - Name of the menu
  identifier = "home"                                 #        - Identifier
  name = "Home"                                       #        - Display name (theme specific key)
  url = "/"                                           #        - Target URL
  weight = 1.0                                        #        - Sorting order

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2.0

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 3.0

[params]                                              # Theme specific parameters
color = "#71B180"
copyright = "Copyright &copy; 2020 Acme Corporation. All Rights Reserved."
style = "green"
logo = "image/logo.png"
logo_small = "image/logo.png"
about_us = "Acme Corporation are the world's leading manufacturer of digital shapes. From squares and circles to triangles and hexagons, we have it all. Browse through our collection of various forms with different thickness and line styles. We shape the world. You live in it."

  [params.recent_posts]
  enable = true

  [[params.footer]]
  title = "About"
  content = "Acme Corporation is the world's leading manufacturer of digital shapes. From squares and circles to triangles and hexagons, we have it all. Browse through our collection of various forms with different thickness and line styles. We shape the world. You live in it."

  [[params.footer]]
  title = "Recent Blog Posts"
  recents = "blog"
  recentCount = 7.0

  [[params.footer]]
  title = "Contact Us"
  contact = true
